import { mutation } from "./_generated/server";

// Seed function to add Commercial Auto Parts products (Taxi, Bakkie, Car spares)
export const seed = mutation({
  handler: async (ctx) => {
    // Clear existing products
    const existingProducts = await ctx.db.query("cars").collect();
    for (const p of existingProducts) {
      await ctx.db.delete(p._id);
    }

    const demoProducts = [
      // TAXI SPARES
      {
        make: "Toyota",
        model: "Quantum Ses'fikile Brake Pad Set",
        year: 2023,
        price: 850,
        mileage: 0,
        fuelType: "New",
        transmission: "Standard Fit",
        engineSize: "2.5 D4D",
        color: "Metallic",
        bodyType: "Taxi",
        description: "Heavy-duty ceramic brake pads specifically engineered for the Toyota Quantum Ses'fikile. High heat dissipation for urban taxi cycles.",
        features: ["SABS Approved", "Low Dust", "High Durability", "Noise Shims Included"],
        images: ["/taxi-brake-parts.png"],
        isAvailable: true,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Nissan",
        model: "NV350 Impendulo Clutch Kit",
        year: 2022,
        price: 2450,
        mileage: 0,
        fuelType: "New",
        transmission: "Manual",
        engineSize: "2.5 Petrol",
        color: "Steel",
        bodyType: "Taxi",
        description: "Original specification clutch kit for Nissan NV350. Includes pressure plate, release bearing, and high-friction plate.",
        features: ["OEM Spec", "Self-Adjusting", "Heavy Duty", "Long Lifecycle"],
        images: ["/taxi-clutch-parts.png"],
        isAvailable: true,
        isFeatured: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      // BAKKIE SPARES
      {
        make: "Ford",
        model: "Ranger T6 Front Shocks",
        year: 2021,
        price: 1800,
        mileage: 0,
        fuelType: "New",
        transmission: "4x4 / 4x2",
        engineSize: "2.2 / 3.2 TDCi",
        color: "Black",
        bodyType: "Bakkie",
        description: "Premium gas-charged front shock absorbers for Ford Ranger T6. Enhanced stability for heavy loads and off-road conditions.",
        features: ["Nitro Gas", "Direct Fit", "Enhanced Comfort", "2-Year Warranty"],
        images: ["/car-suspension-parts.png"],
        isAvailable: true,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Isuzu",
        model: "D-Max Headlight Assembly (RHS)",
        year: 2020,
        price: 3200,
        mileage: 0,
        fuelType: "New",
        transmission: "Projector Type",
        engineSize: "All Models",
        color: "Clear",
        bodyType: "Bakkie",
        description: "Complete right-hand side headlight assembly for Isuzu D-Max. Includes housing and lens. Excludes bulbs.",
        features: ["UV Protected Lens", "Perfect Alignment", "E-Marked", "Durable Plastic"],
        images: ["/taxi-body-panels.png"],
        isAvailable: true,
        isFeatured: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      // CAR SPARES
      {
        make: "Volkswagen",
        model: "Golf 7 Service Kit",
        year: 2022,
        price: 1350,
        mileage: 0,
        fuelType: "New",
        transmission: "TSI / TDI",
        engineSize: "1.4 / 2.0",
        color: "Assorted",
        bodyType: "Car",
        description: "Complete major service kit for VW Golf 7. Includes Oil Filter, Air Filter, Cabin Filter, and Spark Plugs.",
        features: ["German Filters", "Platinum Plugs", "Original Grades", "Instruction Manual"],
        images: ["/car-service-kits.png"],
        isAvailable: true,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "BMW",
        model: "3 Series F30 Control Arm (Front Lower)",
        year: 2019,
        price: 1950,
        mileage: 0,
        fuelType: "New",
        transmission: "E90/F30",
        engineSize: "All Models",
        color: "Aluminium",
        bodyType: "Car",
        description: "Front lower control arm with pre-pressed bushing for BMW 3 Series. High-grade aluminium construction for weight reduction.",
        features: ["Pre-bushed", "Lightweight Al", "OEM Geometry", "Precision Cast"],
        images: ["/car-drivetrain-parts.png"],
        isAvailable: true,
        isFeatured: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      // COOLING (RADIATOR CENTRE)
      {
        make: "Radiator",
        model: "Toyota Hilux GD-6 Aluminium Radiator",
        year: 2023,
        price: 3800,
        mileage: 0,
        fuelType: "New",
        transmission: "Manual / Auto",
        engineSize: "2.4 / 2.8 GD-6",
        color: "Silver",
        bodyType: "Cooling",
        description: "High-efficiency full aluminium radiator for Toyota Hilux GD-6. 3-core design for maximum cooling in extreme SA conditions.",
        features: ["Full Aluminium", "3-Core Design", "Direct Replacement", "Leak Tested"],
        images: ["/aluminium-radiator.png"],
        isAvailable: true,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Locksets",
        model: "VW Polo Vivo Ignition Barrel & Key",
        year: 2018,
        price: 1200,
        mileage: 0,
        fuelType: "New",
        transmission: "Coding Required",
        engineSize: "All Models",
        color: "Steel",
        bodyType: "Lock",
        description: "Replacement ignition barrel for VW Polo Vivo. Includes 2 keys. High-security tumbler design.",
        features: ["Hardened Steel", "Anti-Pick set", "Precision Key", "Standard Fit"],
        images: ["/mag-rim-black.png"],
        isAvailable: true,
        isFeatured: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      }
    ];

    for (const product of demoProducts) {
      await ctx.db.insert("cars", product);
    }

    return { message: "Commercial Auto Parts Catalog Seeded Successfully", count: demoProducts.length };
  },
});
