import { mutation } from "./_generated/server";

// Seed function to add Wheelworx specific products (Rims, Mags, Tyres) using local assets
export const seed = mutation({
  handler: async (ctx) => {
    // Clear existing products
    const existingProducts = await ctx.db.query("cars").collect();
    for (const p of existingProducts) {
      await ctx.db.delete(p._id);
    }

    const demoProducts = [
      {
        make: "Vossen",
        model: "HF-2 Tinted Gloss Black",
        year: 2024,
        price: 12500,
        mileage: 0,
        fuelType: "N/A",
        transmission: "N/A",
        engineSize: "20 inch",
        color: "Gloss Black",
        bodyType: "Rim",
        description: "Hybrid Forged HF-2 wheel in Tinted Gloss Black. Part of the Vossen Hybrid Forged Series. Lightweight and extremely durable.",
        features: ["Hybrid Forged", "Lightweight", "Tinted Finish", "Bespoke Fitment"],
        images: ["/rim-side.png"],
        isAvailable: true,
        isDealOfWeek: true,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Michelin",
        model: "Pilot Sport 4S",
        year: 2024,
        price: 4800,
        mileage: 0,
        fuelType: "N/A",
        transmission: "N/A",
        engineSize: "245/35 ZR20",
        color: "Black",
        bodyType: "Tyre",
        description: "The Michelin Pilot Sport 4S is a maximum performance summer tyre designed for high-performance vehicles. Superior grip and longevity.",
        features: ["Max Performance", "Ultra-High Grip", "Dynamic Response", "Premium Touch Sidewall"],
        images: ["/tire2.png"],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "BBS",
        model: "LM Forged 2-Piece",
        year: 2024,
        price: 15000,
        mileage: 0,
        fuelType: "N/A",
        transmission: "N/A",
        engineSize: "19 inch",
        color: "Gold/Silver",
        bodyType: "Rim",
        description: "The legendary BBS LM. A 2-piece forged wheel with a timeless design. Hand-finished in Germany for ultimate performance.",
        features: ["Forged 2-Piece", "Hand Finished", "German Engineering", "Lightweight Alloy"],
        images: ["/hero-rim.png"],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Pirelli",
        model: "P Zero Corsa",
        year: 2024,
        price: 5200,
        mileage: 0,
        fuelType: "N/A",
        transmission: "N/A",
        engineSize: "265/30 ZR19",
        color: "Black",
        bodyType: "Tyre",
        description: "A tyre that brings the best of track technology to the road. Designed for supercar performance and extreme handling.",
        features: ["Track Ready", "Extreme Handling", "Formula 1 Heritage", "Specialized Compound"],
        images: ["/tyre-side.png"],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Rohana",
        model: "RFX11 Brushed Bronze",
        year: 2023,
        price: 9500,
        mileage: 0,
        fuelType: "N/A",
        transmission: "N/A",
        engineSize: "19 inch",
        color: "Brushed Bronze",
        bodyType: "Mag",
        description: "Cross-Spoke Rotary Forged RFX11. A modern take on a classic mesh design, offering deep concave profiles.",
        features: ["Rotary Forged", "Deep Concave", "Brushed Bronze Finish", "Lightweight"],
        images: ["/mag-collection.png"],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: true,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Continental",
        model: "SportContact 7",
        year: 2024,
        price: 4200,
        mileage: 0,
        fuelType: "N/A",
        transmission: "N/A",
        engineSize: "235/40 R19",
        color: "Black",
        bodyType: "Tyre",
        description: "Continental's flagship performance tyre. Developed for super sports cars, providing ultimate control and braking performance.",
        features: ["Maximum Control", "Adaptive Tread", "BlackChili Compound", "Short Braking"],
        images: ["/tires.png"],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Rotiform",
        model: "LAS-R White",
        year: 2024,
        price: 7800,
        mileage: 0,
        fuelType: "N/A",
        transmission: "N/A",
        engineSize: "18 inch",
        color: "Gloss White",
        bodyType: "Mag",
        description: "Rotiform LAS-R cast monoblock wheels. Featuring a unique multi-spoke design with a specialized aero ring.",
        features: ["Cast Monoblock", "Aero Ring", "Modern Aesthetic", "Concave Face"],
        images: ["/mag-showroom.png"],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      },
      {
        make: "Bridgestone",
        model: "Potenza Sport",
        year: 2024,
        price: 3900,
        mileage: 0,
        fuelType: "N/A",
        transmission: "N/A",
        engineSize: "225/45 R18",
        color: "Black",
        bodyType: "Tyre",
        description: "New Bridgestone Potenza Sport is a high-performance tyre that enables you to maximize the potential of your vehicle.",
        features: ["Stable Cornering", "Wet Handling", "High-Speed Performance", "Precision Steering"],
        images: ["/tyres.png"],
        isAvailable: true,
        isDealOfWeek: false,
        isFeatured: false,
        createdAt: Date.now(),
        updatedAt: Date.now(),
      }
    ];

    for (const product of demoProducts) {
      await ctx.db.insert("cars", product);
    }

    return { message: "Wheelworx Catalog updated with local assets", count: demoProducts.length };
  },
});
